### ISSUE TITLE
"certificate signed by unknown authority" with valid certificates

### ISSUE THREAD

**Issue by draoncc** [pcarranza/nomad-exporter#21]
Trying to run the Docker container configured with TLS fails with the following error:

```
time="2020-05-05T10:11:10Z" level=info msg="Listening on :9441"
time="2020-05-05T10:11:24Z" level=error msg="could not collect leader: Get https://127.0.0.1:4646/v1/status/leader?namespace=default®ion=eu-central-1&wait=10ms: x509: certificate signed by unknown authority"
```

Example configuration:

```
docker run rm --it -p 9441:9441 gitlab.com/yakshaving.art/nomad-exporter:latest -nomad.address https://127.0.0.1:4646 -tls.ca-file /tls/nomad/ca.crt.pem -tls.cert-file /tls/nomad/nomad.crt.pem -tls.key-file /tls/nomad/nomad.key.pem
```

Running the Nomad CLI directly works:

```
$ nomad node status -ca-cert /tls/nomad/ca.crt.pem -client-cert /tls/nomad/nomad.crt.pem -client-key /tls/nomad/nomad.key.pem -address https://127.0.0.1:4646
Error querying node status: Unexpected response code: 403 (Permission denied)
```

(403 is the expected response code as I'm not providing an ACL token.)

---

Digging into the code revealed a 1:1 mapping of args onto `github.com/hashicorp/nomad/api`. Perhaps creating an issue on their side would be more appropriate?

**Comment by pcarranza** [comment]
Most likely, but... if you want to give it a try, everything is go, thus you could try to inject your CA cert in the paths where go will look for them -> https://stackoverflow.com/questions/40051213/where-is-golang-picking-up-root-cas-from

I am doing this in a completely different project and it's just working.

**Comment by draoncc** [comment]
Thank you, that did work! I had incorrectly assumed that providing a CA certificate explicitly wouldn't require me add them there, since curl worked, too. Though now I'm facing a different issue.

```
time="2020-05-07T14:44:06Z" level=error msg="could not collect leader: Get https://10.0.3.187:4646/v1/status/leader?namespace=default®ion=eu-central-1&wait=10ms: remote error: tls: bad certificate"
```

Seems like I should brush up my understanding of TLS. Closing this as it's not a question board. :)
