### ISSUE TITLE
Metric on non eligible boxes

### ISSUE THREAD

**Issue by jesusvazquez** [pcarranza/nomad-exporter#3]
The concept of eligibility is introduced in Nomad 0.8, [here](https://www.nomadproject.io/docs/commands/node/eligibility.html) is the available official documentation.

It would be nice to alert based on non eligible nodes after a threshold of time. E.g. A vm is accidentally restarted, nomad process is started by upstart/systemdb and by default it disables drain mode (Default behaviour in Nomad 0.8), however the box remains non elegible for the scheduler meaning you're wasting resources. 

The objective is to realize about this and be able to alert when this happens.

**Comment by pcarranza** [comment]
Can do

**Comment by pcarranza** [comment]
It's in the [nodes API reply](https://www.nomadproject.io/api/nodes.html#sample-response), this could be included in the node metrics as a label.

Then we can simply alert when we see a node in a non-eligible state (false) for too long.

**Comment by pcarranza** [comment]
Oh, just looking at the code, you already have this: https://github.com/pcarranza/nomad-exporter/blob/master/nomad-exporter.go#L51

The name of the label is `scheduling_eligibility` and it's in the `nomad_node_info` metric.

**Comment by pcarranza** [comment]
Closing as it is already supported
